# We can request to compute an estimate for any verifier
verifier:
  name: CountingProVe
  # Specify
  params:
    cpu_only: True
    rounding: 3
    compute_violation_rate: True
    estimation_points: 10000
    splits: 17
    beta: 0.02
    T: 350
    compute_only_lower_bound: True




# Specify path and type of model
model:
  path: temp_files/model_2_68.h5
  type: keras

# Example of concrete property
property:
  type: concrete
  
  # Choose between SAT / count / enumeration check
  goal: count

  # TODO choose whether to give the possibility of targeting safe or unsafe areas
  target: unsafe

  domain:
    bounds: [[0., 1.], [0., 1.]]
    
  sat_condition:
    # Choose concrete node to check
    num_nodes: 1
    node: 1
    # Specify absolute or relative bounds
    bounds: positive

