# We can request to compute an estimate for any verifier
verifier:
  name: eProVe
  # Specify
  params:
    estimation_points: 3500 # number of points to estimate the volume of the target set, if not specified the verifier will compute the minimum number of points based on the confidence alpha and lower bound R specified
    compute_only_estimation: True # whether to compute only the estimation of the volume of the target set
    R: 0.995 # lower bound of the correctness on the probabilistic result of volume of the target set
    alpha: 0.999 # confidence of the probabilistic result of volume of the target set
    max_depth: 18 # maximum depth of the search tree
    split_node_heuristic: rand # heuristic to choose the node to split
    split_pos_heuristic: median # heuristic to choose the position to split
    rate_tolerance_probability: 0.0001 # the rate under which do not split the node


# Specify path and type of model
model:
  path: ./temp_files/test_patch_model.pt
  type: torch
  input_shape: [1, 4, 4]
  output_shape: [3]

# Example of concrete property
property:
  # Choose between SAT / count / enumeration check
  goal: count

  type: robustness
  use_abstraction: False
  
  # Choose whether to targeting safe or unsafe areas
  target_volume: unsafe

  # Path to folder of VNN-LIB files
  # path: "./example_vnnlibs/CIFAR100_resnet_large_prop_idx_62_sidx_313_eps_0.0039.vnnlib"

  # Property's domain to verify
  domain:
    center: [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
    perturbation_type: upper_threshold
    perturbation: 1.0
    patch_size: [ 1, 2, 2 ]

  # Specify the postcondition to check: positive or negative, range, max or min value w.r.t. all the other nodes
  sat_condition:
    # Choose concrete node to check
    node_index: 1
    # Condition to check
    node_condition: [-1000.0, 1000.0]