# We can request to compute an estimate for any verifier
verifier:
  name: ProVe
  # Specify
  params:
    cpu_only: True/False
    time_out_cycle: 60
    time_out_checked: 0
    interval_propagation_type: naive/symbolic/relaxation
    memory_limit: 0
    disk_limit: 0
    rounding: 3
    estimation_points: 1000000


# Specify path and type of model
model:
  path: temp_files/model_2_68.h5
  type: keras/torch/onnx

# Example of concrete property
property:
  type: concrete
  
  # Choose between SAT / count / enumeration check
  goal: count

  # TODO choose whether to give the possibility of targeting safe or unsafe areas
  target_volume: unsafe/safe

  domain:
    bounds: [[0., 1.], [0., 1.]]
    
  sat_condition:
    # Choose concrete node to check
    num_nodes: 1
    node: 0
    # Specify absolute or relative bounds
    bounds: [0.000000001, inf]


# Example of abstract property
property:
  type: concrete
  
  # Choose between SAT / count / enumeration check
  goal: count

  # TODO choose whether to give the possibility of targeting safe or unsafe areas
  target_volume: unsafe/safe

  domain:
    bounds: [[0., 1.], [0., 1.]]
    
  sat_condition:
    # Choose concrete node to check
    num_nodes: 1
    node: 0
    # Specify absolute or relative bounds
    bounds: [0.000000001, inf]

