# We can request to compute an estimate for any verifier
verifier:
  name: CountingProVe
  # Specify
  params:
    cpu_only: True
    rounding: 3
    compute_violation_rate: True
    estimation_points: 1500000
    S: 17
    beta: 0.02
    T: 350
    compute_only_lower_bound: False




# Specify path and type of model
model:
  path: temp_files/model_2_68.h5
  type: keras

# Example of concrete property
property:
  # Input domain
  domain: [[0,1], [0,1]]
  
